# Generated by Django 3.1.6 on 2021-03-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210315_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorpost',
            options={'verbose_name': 'Post Author', 'verbose_name_plural': 'Post Authors'},
        ),
    ]
