# Generated by Django 3.1.6 on 2021-03-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210317_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendpost',
            name='images_en',
        ),
        migrations.RemoveField(
            model_name='extendpost',
            name='images_ky',
        ),
        migrations.RemoveField(
            model_name='extendpost',
            name='images_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogger_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogger_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blogger_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_ky',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_ru',
        ),
        migrations.AddField(
            model_name='authorpost',
            name='short_intro_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authorpost',
            name='short_intro_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='authorpost',
            name='short_intro_ru',
            field=models.TextField(null=True),
        ),
    ]
