# Generated by Django 3.1.6 on 2021-03-16 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210315_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday_en',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_ky',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_ru',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_en',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_ky',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_ru',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_en',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Specified')], default='NS', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_ky',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Specified')], default='NS', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender_ru',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Specified')], default='NS', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ky',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ky',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_en',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_ky',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_ru',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username_ky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
