# Generated by Django 3.1.6 on 2021-03-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210317_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_ky',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username_ru',
        ),
    ]
