# Generated by Django 3.1.6 on 2021-03-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210317_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
