# Generated by Django 3.1.6 on 2021-03-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('slug', models.SlugField(blank=True, choices=[('news', 'News'), ('diet', 'Diet'), ('exercises', 'Exercises'), ('life-style', 'Life-Style')], max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('logo', models.FileField(blank=True, null=True, upload_to='category_logo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.categorypost')),
            ],
            options={
                'verbose_name': 'Post Category',
                'verbose_name_plural': 'Post Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('slug', models.SlugField(blank=True, choices=[('comfort', 'Comfort'), ('open', 'Open')], max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('logo', models.FileField(blank=True, null=True, upload_to='category_logo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.categoryoffer')),
            ],
            options={
                'verbose_name': 'Offer Category',
                'verbose_name_plural': 'Offer Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryClub',
            fields=[
                ('slug', models.SlugField(blank=True, choices=[('gym', 'Fitness-Centers'), ('pool', 'Pools'), ('yoga', 'Yoga-Studios')], max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=60)),
                ('logo', models.FileField(blank=True, null=True, upload_to='category_logo')),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.categoryclub')),
            ],
            options={
                'verbose_name': 'Club Category',
                'verbose_name_plural': 'Club Categories',
            },
        ),
    ]
