# Generated by Django 3.1.6 on 2021-02-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryclub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
