# Generated by Django 3.1.6 on 2021-03-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210317_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryclub',
            name='parent_en',
        ),
        migrations.RemoveField(
            model_name='categoryclub',
            name='parent_ky',
        ),
        migrations.RemoveField(
            model_name='categoryclub',
            name='parent_ru',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='title_en',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='title_ky',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='title_ru',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
