# Generated by Django 3.1.6 on 2021-02-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1 MONTH', '1 месяц'), ('3 MONTHS', '3 месяца')], max_length=55)),
                ('price', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='category.categoryoffer')),
            ],
        ),
    ]
