# Generated by Django 3.1.6 on 2021-03-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerhistory',
            options={'verbose_name': 'Offer History', 'verbose_name_plural': 'Offer History'},
        ),
    ]
