# Generated by Django 3.1.6 on 2021-03-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='expire_date',
        ),
    ]
