# Generated by Django 3.1.6 on 2021-03-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20210310_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='duration',
            field=models.CharField(choices=[('30', '30 days'), ('90', '90 days')], max_length=55),
        ),
    ]
