# Generated by Django 3.1.6 on 2021-03-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210317_0140'),
        ('card', '0004_auto_20210315_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='duration_en',
            field=models.CharField(choices=[('30', '30 days'), ('90', '90 days')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='duration_ky',
            field=models.CharField(choices=[('30', '30 days'), ('90', '90 days')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='duration_ru',
            field=models.CharField(choices=[('30', '30 days'), ('90', '90 days')], max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_ky',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='price_ru',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='category.categoryoffer'),
        ),
        migrations.AddField(
            model_name='card',
            name='type_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='category.categoryoffer'),
        ),
        migrations.AddField(
            model_name='card',
            name='type_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='category.categoryoffer'),
        ),
    ]
