# Generated by Django 3.1.6 on 2021-03-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20210317_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='duration_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='duration_ky',
        ),
        migrations.RemoveField(
            model_name='card',
            name='duration_ru',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_ky',
        ),
        migrations.RemoveField(
            model_name='card',
            name='price_ru',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type_ky',
        ),
        migrations.RemoveField(
            model_name='card',
            name='type_ru',
        ),
    ]
