# Generated by Django 3.1.6 on 2021-02-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, default='classes-1.jpg', null=True, upload_to='club_images'),
        ),
    ]
