# Generated by Django 3.1.6 on 2021-03-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20210317_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='area_en',
        ),
        migrations.RemoveField(
            model_name='club',
            name='area_ky',
        ),
        migrations.RemoveField(
            model_name='club',
            name='area_ru',
        ),
        migrations.RemoveField(
            model_name='club',
            name='gender_segregation_en',
        ),
        migrations.RemoveField(
            model_name='club',
            name='gender_segregation_ky',
        ),
        migrations.RemoveField(
            model_name='club',
            name='gender_segregation_ru',
        ),
        migrations.RemoveField(
            model_name='club',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='club',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='club',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='club',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='club',
            name='phone_ky',
        ),
        migrations.RemoveField(
            model_name='club',
            name='phone_ru',
        ),
    ]
