# Generated by Django 3.1.6 on 2021-03-20 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20210317_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='type',
            new_name='type_category',
        ),
    ]
